name: CargaExpress Flutter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'
          channel: stable

      - name: Obtener dependencias
        run: flutter pub get

      - name: Analizar proyecto
        run: flutter analyze --no-fatal-infos

      - name: Compilar APK
        run: flutter build apk --release

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: CargaExpress-APK
          path: build/app/outputs/flutter-apk/app-release.apk